"""
Configuration Constants for Tur Dal Production Optimization
"""

# Thermodynamics & Physics
SPECIFIC_HEAT_PULSE_KJ_KG_C = 1.8  # kJ/kg.C (1800 J/kgK)
LATENT_HEAT_WATER_KJ_KG = 2260.0  # kJ/kg
AMBIENT_TEMP_KELVIN = 298.0  # 25C
ACTIVATION_ENERGY_J_MOL = 250000.0  # 250 kJ/mol (Protein Denaturation)
FREQUENCY_FACTOR_A = 1e13  # Arrhenius Pre-exponential factor
GAS_CONSTANT_J_MOL_K = 8.314

# Grinding Physics
HEAT_CONVERSION_EFFICIENCY = 0.7  # Eta
CONVECTION_COEFF_W_M2K = 15.0  # h
CASING_AREA_M2 = 0.25  # A

# Production Economics (INR)
ELECTRICITY_RATE_INR_KWH = 12.0
LABOR_COST_INR_HR_BASE = 150.0
RAW_MATERIAL_COST_INR_KG = 55.0  # Tur Khanda
DEFECT_PENALTY_MULTIPLIER = 1.5
RND_AMORTIZATION_YEARS = 5
ANNUAL_OPERATING_HOURS = 3000

# Machinery Parameters
# Ball Mill
BALL_MILL_CAPEX = 450000.0
BALL_MILL_POWER_KW = 7.5
BALL_MILL_WEAR_INR_HR = 5.0
BALL_MILL_FAILURE_PROB = 0.001

# Hammer Mill
HAMMER_MILL_CAPEX = 150000.0
HAMMER_MILL_POWER_KW = 10.0
HAMMER_MILL_WEAR_INR_HR = 45.0
HAMMER_MILL_FAILURE_PROB = 0.01

# Mixie Cluster (Per Unit)
MIXIE_UNIT_CAPEX = 12000.0
MIXIE_UNIT_POWER_KW_PEAK = 0.75
MIXIE_UNIT_WEAR_INR_HR = 8.0
MIXIE_UNIT_FAILURE_PROB = 0.02  # Per unit per hour
MIXIE_CLUSTER_SIZE = 10

# Drying
HEAT_PUMP_COP = 3.5
ELECTRIC_HEATER_COP = 0.9

# Simulation
NUM_BATCHES = 1_000_000
